### ISSUE TITLE
how to do it using keras

### ISSUE THREAD

**Issue by alyato** [dlaptev/TI-pooling#4]
hi @dlaptev, Thanks. But it does't have the  code using the keras.
Do you give  Some advice to do it  using keras? or rewritten by keras.
I know that keras support the TensorFollow, but i use the theano as the backend. Thanks.

**Comment by dlaptev** [comment]
Hi @alyato, thanks for your interest.

I agree, Keras support would be great, but unfortunately we do not have plans on implementing it at least at this moment in time (and neither Theano support).

If you are willing to contribute, please, feel free to look into it and ask for help in the process.
