### ISSUE TITLE
Architecture for a dataset with bigger images

### ISSUE THREAD

**Issue by mortezamg63** [dlaptev/TI-pooling#6]
I have several questions in respect of applying your model for other applications:
I have a dataset with big images.  Do I have to change architecture of your default network for using in other datasets?
I want to know what happens if  reduce the number of layers in you model (mentioned in paper)? In other words, it is a big opaque spot for me whether I can take your model's convolutional layers and use them   as the first layers of my convolutional network to make it rotation invariant? 
Moreover, whether reduce_max among extracted features from parallel model has bad effect on result of my new network or not since data are a little different than normal situation in previous works?

Thanks you in advance for giving your time to me.

**Comment by dlaptev** [comment]
Hi @mortezamg63, thanks for your interest in TI-pooling.

Unfortunately, the example model only works with images of a fixed size: 32x32x1. The model consists of three convolutional+max-pooling layers. This gradually reduces the image size from 32x32 (initial) to 4x4 (after `conv3`), then inputs are flattened to a vector. If you make the inputs larger, you will also need to change the model: most probably add more layers to reduce the inputs to a reasonable size.

As for the transformation invariance, it is actually achieved through [`reduce_max`](https://github.com/dlaptev/TI-pooling/blob/41bb343b115fa92eecfc5fbf9c3f9308ca9d1ae7/tensorflow/rot_mnist12K_model.py#L88). Without this operator on top of parallel models there would be no invariance, so this is the part you probably want to keep.

So if you want to adapt the code to your data, you will need to change [`single_branch`](https://github.com/dlaptev/TI-pooling/blob/41bb343b115fa92eecfc5fbf9c3f9308ca9d1ae7/tensorflow/rot_mnist12K_model.py#L42) definition to work with the data of different size. Then all the branches will handle your data correctly and [`ti_pooled`](https://github.com/dlaptev/TI-pooling/blob/41bb343b115fa92eecfc5fbf9c3f9308ca9d1ae7/tensorflow/rot_mnist12K_model.py#L88) tensor will represent transformation-invariant features. Also do not forget to change the [transformer function](https://github.com/dlaptev/TI-pooling/blob/41bb343b115fa92eecfc5fbf9c3f9308ca9d1ae7/tensorflow/tools.py#L35).

**Comment by mortezamg63** [comment]
Hi **dlaptev**
Thanks a lot for your kind reply.
